server:
  port: 8080

# 数据源配置
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/github?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false

mybatis:
  # 定义xml映射文件的位置
  mapper-locations: classpath:mapper/*.xml

# 日志相关配置
logging:
  config: classpath:log4j2.xml
  level:
    com.zhuzb.github: debug